import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent.parent))
from src.downloader import parse_timestamp
from typing import Any, Dict, List, Optional, Union

# FX builder helper
def make_fx(fx_type: str, **settings: Any) -> Union[str, Dict[str, Any]]:
    """Formats FX blocks into typed dictionaries or 'None' strings."""
    if fx_type == "None" or not fx_type:
        return "None"
    return {"type": fx_type, "settings": settings}

ANCHOR_PRESETS = [
    {
        "song_title": "sanitarium rhythm clean",
        "artist": "metallica",
        "youtube_url": "https://www.youtube.com/watch?v=8V7xhAlp2Sg",
        "start_time": parse_timestamp("00:00"),  
        "amp_model": "Twin Clean",
        "gain": 3.0,
        "volume": 4.2,
        "treble": 8.0,
        "middle": 5.0,
        "bass": 4.0,
        "stomp_fx": make_fx("5 Band EQ", low=2.0, low_mid=-1.5, mid=-12.0, high_mid=10.0, high=7.5),
        "mod_fx": make_fx("Chorus", level=9.0, speed=4.6, depth=3.5),
        "delay_fx": make_fx("Echo", level=1.5, time=400, feedback=3.2, wow=5.5),
        "reverb_fx": make_fx("Arena", level=3.0, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Glory Box",
        "artist": "Portishead",
        "youtube_url": "https://www.youtube.com/watch?v=4qQyUi4zfDs",
        "start_time": parse_timestamp("01:37"),  
        "amp_model": "Champ",
        "gain": 3.0,
        "volume": 5.0,
        "treble": 5.5,
        "middle": 5.5,
        "bass": 5.0,
        "stomp_fx": make_fx("Big Fuzz", level=9.0, tone=5.0, sustain=5.0),
        "mod_fx": make_fx("Vibratone", level=7.5, speed=7.0, depth=4.5, feedback=7.0, phase=5.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.0, decay=5.0, tone=5.0),
    },
    {
        "song_title": "Tom Sawyer",
        "artist": "Rush",
        "youtube_url": "https://www.youtube.com/watch?v=MNrI4MSTXBU",
        "start_time": parse_timestamp("00:52"),  # main riff enters
        "amp_model": "50s Twin",
        "gain": 10.0,
        "volume": 8.0,
        "treble": 7.0,
        "middle": 9.5,
        "bass": 4.5,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Flanger", level=6.0, speed=3.0, depth=7.0, feedback=8.0),
        "delay_fx": make_fx("Delay", level=3.0, time=400, feedback=6.5, tone=3.5),
        "reverb_fx": make_fx("Small Room", level=5.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Stick It Out",
        "artist": "Rush",
        "youtube_url": "https://www.youtube.com/watch?v=ZNnWEZeJqoc",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Burn",
        "gain": 8.4,
        "volume": 5.7,
        "treble": 10.0,
        "middle": 1.0,
        "bass": 4.5,
        "stomp_fx": make_fx("5 Band EQ", low=0.0, low_mid=0.0, mid=2.0, high_mid=0.0, high=-7.5),
        "mod_fx": make_fx("Chorus", level=10.0, speed=1.3, depth=3.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("None"),
    },
    {
        "song_title": "Xanadu",
        "artist": "Rush",
        "youtube_url": "https://www.youtube.com/watch?v=SEuOoMprDqg",
        "start_time": parse_timestamp("07:35"),  # guitar solo section
        "amp_model": "Burn",
        "gain": 10.0,
        "volume": 4.9,
        "treble": 8.9,
        "middle": 7.6,
        "bass": 4.1,
        "stomp_fx": make_fx("Myth Drive", level=10.0, gain=5.0, treble=5.0),
        "mod_fx": make_fx("Chorus", level=6.6, speed=3.1, depth=2.7),
        "delay_fx": make_fx("Echo", level=2.9, time=200, feedback=3.0, wow=3.0),
        "reverb_fx": make_fx("Small Room", level=5.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Mardy Bum",
        "artist": "Arctic Monkeys",
        "youtube_url": "https://www.youtube.com/watch?v=XMRnlCpTWI4",
        "start_time": parse_timestamp("00:00"),  # clean intro riff
        "amp_model": "Twin Clean",
        "gain": 4.0,
        "volume": 5.7,
        "treble": 6.0,
        "middle": 5.5,
        "bass": 6.0,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=4.5, tone=10.0),
    },
    {
        "song_title": "Riot Van",
        "artist": "Arctic Monkeys",
        "youtube_url": "https://www.youtube.com/watch?v=a62FZZa3fjE",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Princeton",
        "gain": 3.3,
        "volume": 9.0,
        "treble": 7.5,
        "middle": 8.2,
        "bass": 2.5,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("Tremolo", level=7.0, speed=6.4),
        "delay_fx": make_fx("Delay", level=2.5, time=400, feedback=4.3, tone=5.3),
        "reverb_fx": make_fx("Arena", level=4.5, decay=8.5, tone=4.6),
    },
    {
        "song_title": "chase",
        "artist": "batta",
        "youtube_url": "https://www.youtube.com/watch?v=oDba5-eFQJE",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "70s Uk Cln",
        "gain": 9.0,
        "volume": 6.0,
        "treble": 10.0,
        "middle": 4.0,
        "bass": 5.5,
        "stomp_fx": make_fx("Blues Drive", level=8.1, gain=7.6, tone=5.0, blend=5.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("Echo", level=5.0, time=300, feedback=5.0, wow=5.0),
        "reverb_fx": make_fx("Plate", level=1.0, decay=2.5, tone=5.5),
    },
    {
        "song_title": "Apple Cider",
        "artist": "Beabadoobee",
        "youtube_url": "https://www.youtube.com/watch?v=laDnsiKURTQ",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "50s Twin",
        "gain": 4.5,
        "volume": 10.0,
        "treble": 7.0,
        "middle": 10.0,
        "bass": 10.0,
        "stomp_fx": make_fx("Myth Drive", level=6.5, gain=5.0, treble=5.0),
        "mod_fx": make_fx("Chorus", level=10.0, speed=4.0, depth=4.5),
        "delay_fx": make_fx("Delay", level=2.5, time=316, feedback=3.0, tone=4.5),
        "reverb_fx": make_fx("Plate", level=4.0, decay=9.5, tone=1.5),
    },
    {
        "song_title": "Animal Nitrate",
        "artist": "Suede",
        "youtube_url": "https://www.youtube.com/watch?v=i7mEB2wnDLQ",
        "start_time": parse_timestamp("02:07"),
        "amp_model": "60s Uk Cln",
        "gain": 5.0,
        "volume": 9.0,
        "treble": 7.0,
        "middle": 4.0,
        "bass": 5.0,
        "stomp_fx": make_fx("Rock Dirt", level=6.5, distort=5.0, filter=5.0),
        "mod_fx": make_fx("Flanger", level=7.5, speed=3.0, depth=7.0, feedback=8.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Large Hall", level=6.5, decay=4.0, tone=5.0),
    },
    {
        "song_title": "A New England",
        "artist": "Billy Bragg",
        "youtube_url": "https://www.youtube.com/watch?v=sEDlFOd0xsk",
        "start_time": parse_timestamp("00:30"),
        "amp_model": "Twin Clean",
        "gain": 3.0,
        "volume": 6.5,
        "treble": 8.0,
        "middle": 1.5,
        "bass": 8.0,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Plate", level=10.0, decay=2.0, tone=9.0),
    },
    {
        "song_title": "Celebrated Summer",
        "artist": "Husker Du",
        "youtube_url": "https://www.youtube.com/watch?v=lF40NLLSr0s",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Twin Clean",
        "gain": 4.5,
        "volume": 9.0,
        "treble": 3.5,
        "middle": 8.0,
        "bass": 6.0,
        "stomp_fx": make_fx("Fuzz", level=5.0, gain=5.0, vari="loose"),
        "mod_fx": make_fx("Chorus", level=9.0, speed=3.5, depth=2.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Plate", level=2.5, decay=1.5, tone=7.0),
    },
    {
        "song_title": "Samba Pa Ti",
        "artist": "Santana",
        "youtube_url": "https://www.youtube.com/watch?v=timZoOs9ozo",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Champ",
        "gain": 7.5,
        "volume": 3.5,
        "treble": 7.0,
        "middle": 1.0,
        "bass": 5.0,
        "stomp_fx": make_fx("Overdrive", level=3.0, gain=7.5, low=3.0, mid=5.0, high=5.0),
        "mod_fx": make_fx("Touch Wah", level=5.0, thresh=5.0, mode="LO-DOWN", filter="LPF", peak=5.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=5.9, tone=5.5),
    },
    {
        "song_title": "Oh!",
        "artist": "Sleater-Kinney",
        "youtube_url": "https://www.youtube.com/watch?v=oS4KYnLKRRY",
        "start_time": parse_timestamp("00:25"),
        "amp_model": "Super Clean",
        "gain": 6.0,
        "volume": 9.5,
        "treble": 8.5,
        "middle": 7.5,
        "bass": 4.5,
        "stomp_fx": make_fx("Blues Drive", level=9.0, gain=5.5, tone=5.0, blend=5.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("Delay", level=2.0, time=400, feedback=2.0, tone=5.5),
        "reverb_fx": make_fx("None"),
    },
    {
        "song_title": "Freddie's Dead",
        "artist": "Curtis Mayfield",
        "youtube_url": "https://youtu.be/esIQyaGEUFU?si=8Sp0I-XE-IbhqIeV",
        "start_time": parse_timestamp("00:30"),
        "amp_model": "50s Twin",
        "gain": 9.5,
        "volume": 7.0,
        "treble": 5.0,
        "middle": 9.5,
        "bass": 5.0,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("Touch Wah", level=10.0, thresh=5.5, mode="HI-UP", filter="BPF", peak=5.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=4.5, tone=10.0),
    },
    {
        "song_title": "Seventh Wave",
        "artist": "Devin Townsend",
        "youtube_url": "https://www.youtube.com/watch?v=b3-NQvRmo3I",
        "start_time": parse_timestamp("00:20"),
        "amp_model": "90s Rock",
        "gain": 3.5,
        "volume": 7.0,
        "treble": 6.0,
        "middle": 3.5,
        "bass": 6.5,
        "stomp_fx": make_fx("Fuzz", level=5.0, gain=5.0, vari="tight"),
        "mod_fx": make_fx("Flanger", level=7.5, speed=4.5, depth=6.0, feedback=8.0),
        "delay_fx": make_fx("Delay", level=7.0, time=400, feedback=8.5, tone=1.0),
        "reverb_fx": make_fx("Large Hall", level=9.5, decay=6.0, tone=2.0),
    },
    {
        "song_title": "Maggot Brain",
        "artist": "Funkadelic",
        "youtube_url": "https://www.youtube.com/watch?v=4Inr22ZBmdw",
        "start_time": parse_timestamp("02:00"),
        "amp_model": "50s Twin",
        "gain": 3.5,
        "volume": 6.0,
        "treble": 7.0,
        "middle": 4.5,
        "bass": 6.0,
        "stomp_fx": make_fx("Fuzz", level=5.0, gain=5.0, vari="loose"),
        "mod_fx": make_fx("Touch Wah", level=7.5, thresh=4.0, mode="LO-DOWN", filter="LPF", peak=7.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=6.0, tone=5.5),
    },
    {
        "song_title": "Panama",
        "artist": "Van Halen",
        "youtube_url": "https://www.youtube.com/watch?v=YRFKU6QvBJY",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "80s Rock",
        "gain": 10.0,
        "volume": 5.0,
        "treble": 10.0,
        "middle": 1.0,
        "bass": 6.0,
        "stomp_fx": make_fx("Myth Drive", level=7.0, gain=5.0, treble=5.0),
        "mod_fx": make_fx("Chorus", level=6.6, speed=3.1, depth=2.7),
        "delay_fx": make_fx("Echo", level=2.9, time=200, feedback=3.0, wow=3.0),
        "reverb_fx": make_fx("Small Room", level=5.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "The Good, the Bad and the Ugly (Main Theme)",
        "artist": "Ennio Morricone",
        "youtube_url": "https://www.youtube.com/watch?v=iE5CkYe6ASg",
        "start_time": parse_timestamp("01:00"),
        "amp_model": "50s Twin",
        "gain": 7.5,
        "volume": 7.0,
        "treble": 5.0,
        "middle": 7.0,
        "bass": 5.0,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Tremolo", level=6.5, speed=5.5),
        "delay_fx": make_fx("Echo", level=3.0, time=316, feedback=8.5, wow=8.5),
        "reverb_fx": make_fx("Plate", level=9.0, decay=2.5, tone=5.0),
    },
    {
        "song_title": "Give Me the Night",
        "artist": "George Benson",
        "youtube_url": "https://www.youtube.com/watch?v=FIF7wKJb2iU",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Super Clean",
        "gain": 2.5,
        "volume": 4.5,
        "treble": 5.5,
        "middle": 6.0,
        "bass": 5.0,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("Chorus", level=3.2, speed=1.2, depth=2.5),
        "delay_fx": make_fx("Delay", level=2.3, time=325, feedback=2.5, tone=4.0),
        "reverb_fx": make_fx("Spring 65", level=2.5, decay=2.5, tone=2.5),
    },
    {
        "song_title": "Coffee & TV",
        "artist": "Blur",
        "youtube_url": "https://www.youtube.com/watch?v=cHrNTR05voQ",
        "start_time": parse_timestamp("00:30"),
        "amp_model": "60s Uk Cln",
        "gain": 4.5,
        "volume": 7.0,
        "treble": 5.0,
        "middle": 8.5,
        "bass": 6.5,
        "stomp_fx": make_fx("Rock Dirt", level=2.5, distort=5.0, filter=5.0),
        "mod_fx": make_fx("Flanger", level=6.5, speed=3.0, depth=6.5, feedback=7.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Arena", level=3.0, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Apache",
        "artist": "The Shadows",
        "youtube_url": "https://www.youtube.com/watch?v=Px_krd_edFI",
        "start_time": parse_timestamp("00:20"),
        "amp_model": "Twin Clean",
        "gain": 4.0,
        "volume": 7.0,
        "treble": 7.0,
        "middle": 8.0,
        "bass": 6.5,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("Tremolo", level=8.0, speed=5.5),
        "delay_fx": make_fx("Echo", level=4.0, time=299, feedback=1.0, wow=5.5),
        "reverb_fx": make_fx("Plate", level=9.5, decay=3.5, tone=1.5),
    },    
    {
        "song_title": "Motorcycle Emptiness",
        "artist": "Manic Street Preachers",
        "youtube_url": "https://www.youtube.com/watch?v=gavcjNniIvk",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "70s Uk Cln",
        "gain": 5.0,
        "volume": 8.0,
        "treble": 4.0,
        "middle": 7.0,
        "bass": 3.0,
        "stomp_fx": make_fx("Rock Dirt", level=6.0, distort=5.0, filter=5.0),
        "mod_fx": make_fx("Chorus", level=7.0, speed=4.5, depth=3.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Small Room", level=3.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "One",
        "artist": "Metallica",
        "youtube_url": "https://www.youtube.com/watch?v=WM8bTdBs-cw",
        "start_time": parse_timestamp("04:10"),
        "amp_model": "70s Uk Cln",
        "gain": 10.0,
        "volume": 5.5,
        "treble": 10.0,
        "middle": 1.0,
        "bass": 5.0,
        "stomp_fx": make_fx("Myth Drive", level=4.0, gain=5.0, treble=5.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Plate", level=4.7, decay=7.0, tone=5.5),
    },
    {
        "song_title": "Voodoo Child (Slight Return)",
        "artist": "Jimi Hendrix",
        "youtube_url": "https://www.youtube.com/watch?v=C0XwPUFfFwE",
        "start_time": parse_timestamp("00:46"),
        "amp_model": "60s Uk Cln",
        "gain": 6.5,
        "volume": 8.0,
        "treble": 3.5,
        "middle": 5.5,
        "bass": 4.6,
        "stomp_fx": make_fx("Fuzz", level=5.0, gain=5.0, vari="loose"),
        "mod_fx": make_fx("Touch Wah", level=5.0, thresh=5.5, mode="HI-UP", filter="BPF", peak=5.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Where Is My Mind?",
        "artist": "Pixies",
        "youtube_url": "https://www.youtube.com/watch?v=tPgf_btTFlc",
        "start_time": parse_timestamp("00:10"),
        "amp_model": "Super Clean",
        "gain": 4.5,
        "volume": 9.5,
        "treble": 6.5,
        "middle": 5.5,
        "bass": 4.0,
        "stomp_fx": make_fx("Myth Drive", level=6.0, gain=5.0, treble=5.0),
        "mod_fx": make_fx("Chorus", level=3.5, speed=5.0, depth=6.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Plate", level=3.5, decay=7.0, tone=4.5),
    },
    {
        "song_title": "Spellbound",
        "artist": "Siouxsie and the Banshees",
        "youtube_url": "https://www.youtube.com/watch?v=TjvvK-Rj0WI",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "50s Twin",
        "gain": 3.0,
        "volume": 6.0,
        "treble": 10.0,
        "middle": 8.0,
        "bass": 7.0,
        "stomp_fx": make_fx("Myth Drive", level=5.0, gain=5.0, treble=5.0),
        "mod_fx": make_fx("Chorus", level=8.5, speed=4.5, depth=6.0),
        "delay_fx": make_fx("Echo", level=2.5, time=125, feedback=3.5, wow=10.0),
        "reverb_fx": make_fx("Arena", level=2.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Creep",
        "artist": "Radiohead",
        "youtube_url": "https://www.youtube.com/watch?v=XFkzRNyygfk",
        "start_time": parse_timestamp("02:03"),
        "amp_model": "90s Rock",
        "gain": 5.0,
        "volume": 7.5,
        "treble": 6.0,
        "middle": 7.5,
        "bass": 3.0,
        "stomp_fx": make_fx("Blues Drive", level=3.0, gain=9.5, tone=5.0, blend=5.0),
        "mod_fx": make_fx("Chorus", level=10.0, speed=2.0, depth=2.0),
        "delay_fx": make_fx("Echo", level=6.0, time=42, feedback=5.0, wow=4.5),
        "reverb_fx": make_fx("Spring 65", level=9.5, decay=5.5, tone=5.0),
    },
    {
        "song_title": "This Charming Man",
        "artist": "The Smiths",
        "youtube_url": "https://www.youtube.com/watch?v=cJRP3LRcUFg",
        "start_time": parse_timestamp("01:00"),
        "amp_model": "Super Clean",
        "gain": 5.5,
        "volume": 7.0,
        "treble": 4.5,
        "middle": 7.5,
        "bass": 3.5,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("Chorus", level=10.0, speed=4.0, depth=4.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=4.0, decay=4.0, tone=5.5),
    },
    {
        "song_title": "Flip the Switch",
        "artist": "The Rolling Stones",
        "youtube_url": "https://www.youtube.com/watch?v=dbm1dWfZej8",
        "start_time": parse_timestamp("01:00"),
        "amp_model": "80s Rock",
        "gain": 7.0,
        "volume": 10.0,
        "treble": 8.0,
        "middle": 4.5,
        "bass": 9.5,
        "stomp_fx": make_fx("Big Fuzz", level=7.5, tone=5.0, sustain=5.0),
        "mod_fx": make_fx("Phaser", level=2.0, speed=4.0, depth=6.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Plate", level=10.0, decay=5.5, tone=4.5),
    },
    {
        "song_title": "Smells Like Teen Spirit",
        "artist": "Nirvana",
        "youtube_url": "https://www.youtube.com/watch?v=hTWKbfoikeg",
        "start_time": parse_timestamp("01:00"),
        "amp_model": "60s Uk Cln",
        "gain": 3.0,
        "volume": 8.0,
        "treble": 10.0,
        "middle": 10.0,
        "bass": 5.0,
        "stomp_fx": make_fx("Fuzz", level=5.5, gain=10.0, vari="tight"),
        "mod_fx": make_fx("Chorus", level=9.5, speed=3.0, depth=8.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("None"),
    },
    {
        "song_title": "Come as You Are",
        "artist": "Nirvana",
        "youtube_url": "https://www.youtube.com/watch?v=vabnZ9-ex7o",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "60s Uk Cln",
        "gain": 3.0,
        "volume": 8.0,
        "treble": 10.0,
        "middle": 10.0,
        "bass": 5.0,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Chorus", level=9.5, speed=3.0, depth=8.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("None"),
    },
    {
        "song_title": "Paperback Writer",
        "artist": "The Beatles",
        "youtube_url": "https://www.youtube.com/watch?v=yYvkICbTZIQ",
        "start_time": parse_timestamp("01:20"),
        "amp_model": "70s Uk Cln",
        "gain": 7.0,
        "volume": 6.0,
        "treble": 6.0,
        "middle": 6.0,
        "bass": 4.5,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("Echo", level=2.0, time=145, feedback=2.5, wow=8.0),
        "reverb_fx": make_fx("None"),
    },
    {
        "song_title": "Chamber of Reflection",
        "artist": "Mac DeMarco",
        "youtube_url": "https://www.youtube.com/watch?v=jja0UmQZ6vY",
        "start_time": parse_timestamp("00:42"),
        "amp_model": "Twin Clean",
        "gain": 5.0,
        "volume": 6.5,
        "treble": 5.4,
        "middle": 4.4,
        "bass": 8.2,
        "stomp_fx": make_fx("Sustain", sense=5.0, level=5.0),
        "mod_fx": make_fx("Chorus", level=10.0, speed=4.5, depth=3.0),
        "delay_fx": make_fx("Delay", level=4.0, time=180, feedback=5.5, tone=5.5),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=5.9, tone=1.0),
    },
    {
        "song_title": "Jockey Full of Bourbon",
        "artist": "Tom Waits",
        "youtube_url": "https://www.youtube.com/watch?v=ipQgbKEK4s0",
        "start_time": parse_timestamp("01:20"),
        "amp_model": "50s Twin",
        "gain": 4.0,
        "volume": 9.0,
        "treble": 5.0,
        "middle": 5.5,
        "bass": 7.5,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Tremolo", level=7.0, speed=3.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=2.5, decay=5.0, tone=5.0),
    },
    {
        "song_title": "Sultans of Swing",
        "artist": "Dire Straits",
        "youtube_url": "https://www.youtube.com/watch?v=h0ffIJ7ZO4U",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Twin Clean",
        "gain": 4.0,
        "volume": 8.0,
        "treble": 7.5,
        "middle": 7.5,
        "bass": 3.0,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("Chorus", level=4.5, speed=5, depth=5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=2.5, decay=5, tone=5.5),
    },
    {
        "song_title": "Enter Sandman",
        "artist": "Metallica",
        "youtube_url": "https://www.youtube.com/watch?v=CD-E-LDc384",
        "start_time": parse_timestamp("00:35"),
        "amp_model": "90s Rock",
        "gain": 9.0,
        "volume": 7.0,
        "treble": 9.0,
        "middle": 1.5,
        "bass": 5.0,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Small Room", level=5.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Moonage Daydream",
        "artist": "David Bowie",
        "youtube_url": "https://www.youtube.com/watch?v=RPUAldgS7Sg",
        "start_time": parse_timestamp("01:27"),
        "amp_model": "70s Rock",
        "gain": 7.0,
        "volume": 9.5,
        "treble": 4.5,
        "middle": 5.5,
        "bass": 7.0,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Large Hall", level=4.0, decay=3.0, tone=7.0),
    },
    {
        "song_title": "Are You Looking Up",
        "artist": "mk.gee",
        "youtube_url": "https://www.youtube.com/watch?v=DxdKr5PmlPw",
        "start_time": parse_timestamp("01:00"),
        "amp_model": "Super Clean",
        "gain": 5.5,
        "volume": 10,
        "treble": 10,
        "middle": 9.1,
        "bass": 9.1,
        "stomp_fx": make_fx("Octobot", direct=1.0, down=7.0, sizzle=5.0),
        "mod_fx": make_fx("Chorus", level=10.0, speed=3.2, depth=3.7),
        "delay_fx": make_fx("Echo", level=1.5, time=290, feedback=4.4, wow=6.8),
        "reverb_fx": make_fx("Plate", level=9, decay=2.7, tone=4.0),
    },
    {
        "song_title": "Last Nite",
        "artist": "The Strokes",
        "youtube_url": "https://www.youtube.com/watch?v=TOypSnKFHrE",
        "start_time": parse_timestamp("01:35"),
        "amp_model": "Burn",
        "gain": 1.8,
        "volume": 5.0,
        "treble": 8.7,
        "middle": 6.6,
        "bass": 4.2,
        "stomp_fx": make_fx("5 Band EQ", low=0.0, low_mid=0.0, mid=12.0, high_mid=0.0, high=0.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=4.5, tone=10.0),
    },
    {
        "song_title": "Good Times",
        "artist": "Chic",
        "youtube_url": "https://www.youtube.com/watch?v=Q5C9oeKxJzo",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Twin Clean",
        "gain": 3.0,
        "volume": 7.0,
        "treble": 6.0,
        "middle": 6.0,
        "bass": 7.5,
        "stomp_fx": make_fx("Compressor", type="mid"),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("Delay", level=5.0, time=483, feedback=3.0, tone=5.5),
        "reverb_fx": make_fx("Small Room", level=4.0, decay=4.5, tone=3.5),
    },
    {
        "song_title": "Unsung",
        "artist": "Helmet",
        "youtube_url": "https://www.youtube.com/watch?v=JcF7W5eloYM",
        "start_time": parse_timestamp("00:12"),
        "amp_model": "90s Rock",
        "gain": 7.5,
        "volume": 5.0,
        "treble": 8.0,
        "middle": 6.0,
        "bass": 9.0,
        "stomp_fx": make_fx("Octobot", direct=8.5, down=5.0, sizzle=5.0),
        "mod_fx": make_fx("Touch Wah", level=2.0, thresh=7.5, mode="HI-UP", filter="BPF", peak=6.5),
        "delay_fx": make_fx("Delay", level=2.0, time=352, feedback=2.5, tone=1.0),
        "reverb_fx": make_fx("Large Hall", level=2.5, decay=7.5, tone=6.0),
    },
    {
        "song_title": "Dress",
        "artist": "PJ Harvey",
        "youtube_url": "https://www.youtube.com/watch?v=4lS5jTedHBg",
        "start_time": parse_timestamp("00:16"),
        "amp_model": "60s Uk Cln",
        "gain": 6.0,
        "volume": 6.0,
        "treble": 5.5,
        "middle": 6.5,
        "bass": 5.0,
        "stomp_fx": make_fx("Rock Dirt", level=3.0, distort=5.0, filter=5.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Large Hall", level=2.0, decay=3.0, tone=10.0),
    },
    {
        "song_title": "Attack of the Ghost Riders",
        "artist": "The Raveonettes",
        "youtube_url": "https://www.youtube.com/watch?v=1gQEvupSrRY",
        "start_time": parse_timestamp("00:55"),
        "amp_model": "Deluxe Cln",
        "gain": 9.5,
        "volume": 4.5,
        "treble": 9.0,
        "middle": 3.5,
        "bass": 7.5,
        "stomp_fx": make_fx("Sustain", sense=5.0, level=5.0),
        "mod_fx": make_fx("Chorus", level=9.0, speed=4.5, depth=1.5),
        "delay_fx": make_fx("Delay", level=3.5, time=400, feedback=5.5, tone=5.5),
        "reverb_fx": make_fx("Large Hall", level=10.0, decay=10.0, tone=8.0),
    },
    {
        "song_title": "All's Well That Ends",
        "artist": "Rainbow Kitten Surprise",
        "youtube_url": "https://www.youtube.com/watch?v=fSOl7lYSE3c",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Twin Clean",
        "gain": 4.5,
        "volume": 5.5,
        "treble": 6.0,
        "middle": 7.5,
        "bass": 6.9,
        "stomp_fx": make_fx("Myth Drive", level=7.0, gain=5.0, treble=5.0),
        "mod_fx": make_fx("Chorus", level=6.5, speed=3.0, depth=2.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Arena", level=7.0, decay=4.7, tone=6.6),
    },
    {
        "song_title": "Play for Today",
        "artist": "The Cure",
        "youtube_url": "https://www.youtube.com/watch?v=_iJ7U1qP7KA",
        "start_time": parse_timestamp("00:30"),
        "amp_model": "Doom Metal",
        "gain": 2.5,
        "volume": 9.5,
        "treble": 10.0,
        "middle": 1.0,
        "bass": 6.5,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Flanger", level=10.0, speed=4.0, depth=4.5, feedback=8.0),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Large Hall", level=4.0, decay=5.0, tone=8.0),
    },
    {
        "song_title": "Pearly-Dewdrops' Drops",
        "artist": "Cocteau Twins",
        "youtube_url": "https://www.youtube.com/watch?v=s-5Xgw6d3h0",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Princeton",
        "gain": 6.5,
        "volume": 9.0,
        "treble": 6.5,
        "middle": 6.5,
        "bass": 6.5,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Chorus", level=10.0, speed=4.5, depth=3.0),
        "delay_fx": make_fx("Delay", level=5.0, time=400, feedback=9.0, tone=1.5),
        "reverb_fx": make_fx("Spring 65", level=8.0, decay=3.5, tone=5.5),
    },
    {
        "song_title": "Helicopter",
        "artist": "Bloc Party",
        "youtube_url": "https://www.youtube.com/watch?v=kkkA85hPtYw",
        "start_time": parse_timestamp("02:15"),
        "amp_model": "Burn",
        "gain": 6.9,
        "volume": 6.5,
        "treble": 3.5,
        "middle": 8.5,
        "bass": 2.0,
        "stomp_fx": make_fx("Sustain", sense=5.0, level=5.0),
        "mod_fx": make_fx("Tremolo", level=9.5, speed=6.5),
        "delay_fx": make_fx("Delay", level=2.5, time=547, feedback=8.0, tone=6.5),
        "reverb_fx": make_fx("Small Room", level=9.0, decay=2.0, tone=5.5),
    },
    {
        "song_title": "Sweet Child O' Mine",
        "artist": "Guns N' Roses",
        "youtube_url": "https://www.youtube.com/watch?v=1w7OgIMMRc4",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "70s Rock",
        "gain": 8.0,
        "volume": 8.0,
        "treble": 10.0,
        "middle": 6.0,
        "bass": 10.0,
        "stomp_fx": make_fx("Blues Drive", level=5.9, gain=10.0, tone=5.0, blend=5.0),
        "mod_fx": make_fx("Touch Wah", level=3.4, thresh=5.5, mode="LO-UP", filter="HPF", peak=5.5),
        "delay_fx": make_fx("Delay", level=2.5, time=226, feedback=5.5, tone=5.5),
        "reverb_fx": make_fx("Arena", level=2.5, decay=5.5, tone=5.5),
    },
    {
        "song_title": "Kannon 1",
        "artist": "Sunn O",
        "youtube_url": "https://www.youtube.com/watch?v=IswnGaGxvRQ",
        "start_time": parse_timestamp("02:30"),
        "amp_model": "Doom Metal",
        "gain": 7.5,
        "volume": 6.0,
        "treble": 8.0,
        "middle": 4.0,
        "bass": 7.0,
        "stomp_fx": make_fx("Fuzz", level=5.0, gain=5.0, vari="loose"),
        "mod_fx": make_fx("Vibratone", level=6.5, speed=10.0, depth=2.5, feedback=7.0, phase=6.0),
        "delay_fx": make_fx("Echo", level=3.0, time=361, feedback=3.0, wow=7.5),
        "reverb_fx": make_fx("Arena", level=5.0, decay=5.5, tone=3.5),
    },
    {
        "song_title": "Firth of Fifth",
        "artist": "Genesis",
        "youtube_url": "https://www.youtube.com/watch?v=Rz-tHZEr37I",
        "start_time": parse_timestamp("06:30"),
        "amp_model": "60s Uk Cln",
        "gain": 4.4,
        "volume": 6.0,
        "treble": 7.0,
        "middle": 4.5,
        "bass": 4.0,
        "stomp_fx": make_fx("Overdrive", level=4.5, gain=5.5, low=5.5, mid=5.0, high=5.0),
        "mod_fx": make_fx("Chorus", level=3.3, speed=2.6, depth=3.5),
        "delay_fx": make_fx("Echo", level=4.8, time=450, feedback=3.4, wow=1.5),
        "reverb_fx": make_fx("Plate", level=3.7, decay=4.0, tone=4.5),
    },
    {
        "song_title": "Kilby Girl",
        "artist": "The Backseat Lovers",
        "youtube_url": "https://www.youtube.com/watch?v=oTwVce9eWb4",
        "start_time": parse_timestamp("01:00"),
        "amp_model": "Twin Clean",
        "gain": 3.6,
        "volume": 5.9,
        "treble": 7.0,
        "middle": 6.0,
        "bass": 4.0,
        "stomp_fx": make_fx("Overdrive", level=5.5, gain=3.6, low=5.5, mid=5.5, high=5.5),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Large Hall", level=3.8, decay=3.2, tone=7.2),
    },
    {
        "song_title": "Maple Syrup",
        "artist": "The Backseat Lovers",
        "youtube_url": "https://www.youtube.com/watch?v=Gl2TEwnacwM",
        "start_time": parse_timestamp("03:25"),
        "amp_model": "Princeton",
        "gain": 7.0,
        "volume": 5.0,
        "treble": 6.0,
        "middle": 4.6,
        "bass": 1.9,
        "stomp_fx": make_fx("Myth Drive", level=7.0, gain=8.0, treble=7.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=5.5, decay=3.2, tone=5.5),
    },
    {
        "song_title": "Every Breath You Take",
        "artist": "The Police",
        "youtube_url": "https://www.youtube.com/watch?v=OMOGaugKpzs",
        "start_time": parse_timestamp("00:00"),
        "amp_model": "Princeton",
        "gain": 3.3,
        "volume": 6.0,
        "treble": 6.5,
        "middle": 4.5,
        "bass": 3.2,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Chorus", level=2.5, speed=3.0, depth=3.5),
        "delay_fx": make_fx("Echo", level=4.0, time=400, feedback=2.5, wow=1.2),
        "reverb_fx": make_fx("Plate", level=2.5, decay=3.0, tone=5.0),
    },
    {
        "song_title": "Shed",
        "artist": "Title Fight",
        "youtube_url": "https://www.youtube.com/watch?v=SE41j8h6P4g",
        "start_time": parse_timestamp("00:10"),
        "amp_model": "80s Rock",
        "gain": 2.0,
        "volume": 7.0,
        "treble": 4.0,
        "middle": 6.0,
        "bass": 8.0,
        "stomp_fx": make_fx("None"),
        "mod_fx": make_fx("Chorus", level=4.0, speed=4.6, depth=3.5),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Large Hall", level=3.8, decay=3.2, tone=7.2),
    },
    {
        "song_title": "Iron Man",
        "artist": "Black Sabbath",
        "youtube_url": "https://www.youtube.com/watch?v=iFgqckcGpDA",
        "start_time": parse_timestamp("00:30"),
        "amp_model": "Twin Clean",
        "gain": 4.5,
        "volume": 6.5,
        "treble": 4.0,
        "middle": 6.5,
        "bass": 2.0,
        "stomp_fx": make_fx("Big Fuzz", level=5.0, tone=5.0, sustain=5.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Large Hall", level=4.0, decay=10.0, tone=1.0),
    },
    {
        "song_title": "Just Like Honey",
        "artist": "The Jesus and Mary Chain",
        "youtube_url": "https://www.youtube.com/watch?v=7EgB__YratE",
        "start_time": parse_timestamp("01:00"),
        "amp_model": "Twin Clean",
        "gain": 3.0,
        "volume": 7.5,
        "treble": 7.0,
        "middle": 6.5,
        "bass": 6.0,
        "stomp_fx": make_fx("Big Fuzz", level=7.5, tone=5.0, sustain=5.0),
        "mod_fx": make_fx("None"),
        "delay_fx": make_fx("None"),
        "reverb_fx": make_fx("Spring 65", level=10.0, decay=6.0, tone=4.5),
    },

]